import { Component, Inject, OnInit, Optional } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogRef } from '@angular/material/dialog';
import { CommonService } from 'src/app/core/services/common.service';
import { HttpClientService } from 'src/app/core/services/httpclient.service';
import { HttpUSPSService } from 'src/app/core/services/httpusps.service';
import { LoaderService } from 'src/app/core/services/loader.service';
import { AlertPopupComponent } from 'src/app/shared/alert-popup/alert-popup.component';

@Component({
  selector: 'app-mail-popup',
  templateUrl: './mail-popup.component.html',
  styleUrls: ['./mail-popup.component.scss'],
  standalone: false
})
export class MailPopupComponent implements OnInit {

  //variable Declaration
  t002ClntObj: any;
  t002clientProObj: any;
  t007_reportlog: any;
  DateRangeString: any;
  clientType: any;
  openModalConfig: any;
  panelClass: any;
  email_errorString: any;
  message_text: any;
  t007_reportlogobj1: any;
  click: boolean = false;

  //Form group declaration
  mailLogFormGroup!: FormGroup;

  constructor(private dialog: MatDialog, private loaderService: LoaderService,
    public dialogRef: MatDialogRef<MailPopupComponent>, private httpClientService: HttpClientService,
    private commonService: CommonService,
    @Optional() @Inject(MAT_DIALOG_DATA) public data: any
  ) {

    this.t002ClntObj = data.t007_reportlogobjResult;
    this.t002clientProObj = data.t007_reportlogobjResult;
    this.t007_reportlog = data.t007_reportlogobj;
    this.DateRangeString = data.DateRangeString;
    this.clientType = data.clienttype;
    this.ClientAcNoDetails();

    this.mailLogFormGroup = new FormGroup({
      Email: new FormControl('')
    });

  }


  ClientAcNoDetails() {

    if (this.DateRangeString == "CROSSYEARRUN") {
      this.openModal("Due to running report across two different invoice years, this report will have to be generated by LJM and emailed to you. Please provide us your email address(s) and the report will be sent to you in 24 hours.");
    }
    else {
      this.openModal("You requested a report that exceeds the file size limit allowed. Please provide us your email address(s) and the report will be sent to you in 24 hours.");
    }
  }

  openModal(alertVal: any) {
    this.openModalConfig = this.dialog.open(AlertPopupComponent, {
      width: '470px',
      height: 'auto',
      data: { pageValue: alertVal },
      panelClass: this.panelClass
    });
  }

  demoloader() {
    setTimeout(() => {
      this.loaderService.hide();
    }, 1000);
  }

  ngOnInit(): void {
    this.dialogRef.keydownEvents().subscribe(event => {
      if (event.key === "Escape") {
        this.close();
      }
    });

    this.dialogRef.backdropClick().subscribe(event => {
      this.close();
    });
  }

  close() {
    this.dialogRef.close();
  }

  btn_click() {

    var validateEmail = true;
    var email = this.mailLogFormGroup.get("Email")?.value;
    var emailsString: String = String(email);
    var emails = emailsString.split(",");

    for (var loop = 0; loop < emails.length; loop++) {
      if (emails[loop] != '') {
        if (!this.validateEmail(emails[loop])) {

          validateEmail = false;
          this.openModal("Please enter valid email");
          break;
        }
      }
      else {
        validateEmail = false;
        this.openModal("Please enter valid email");
        break;
      }
    }
    if (validateEmail == true) {
      this.email_errorString = "";
      this.message_text = "";
      this.t007_reportlogobj1 = this.t002clientProObj;
      this.t007_reportlogobj1["status"] = "PENDING";
      this.t007_reportlogobj1["specialInstructions"] = "MailAdded";
      this.click = !this.click;
      this.httpClientService.runReport(this.t007_reportlogobj1).subscribe({
        next: (result) => {
          this.callAddMailId(result, email);
        }, error: (error) => {
          this.click = !this.click;
          this.openModal("Error in running report");
        }
      });

    }
  }

  validateEmail(field: any) {
    var regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,5}$/;
    return (regex.test(field)) ? true : false;
  }

  callAddMailId(result: any, email: any) {
    let t007reportLogObj: any = {};
    t007reportLogObj["reportLogId"] = result.reportLogId;
    t007reportLogObj["login_id"] = result.login_id;
    t007reportLogObj["emailId"] = email;
    if (this.DateRangeString == "CROSSYEARRUN") {
      var checkCrossYear = "CROSSYEARRUN";
    } else {
      checkCrossYear = "BATCH";
    }
    t007reportLogObj["checkCrossYear"] = checkCrossYear;
    this.httpClientService.addMailId(t007reportLogObj).subscribe({
      next: (result) => {
        this.addMailIdResult(result);
      }, error: (error) => {
      }
    });
  }

  addMailIdResult(event: any) {
    var message;
    this.openModal("Your request has been added to the report queue. When complete, your file will be downloaded automatically.");
    this.click = !this.click;
    this.dialogRef.close();
  }

}